app_avalia_filmes/urls.py
from django.urls import path,include
from .views import *

app_name = 'avaliador'

urlpatterns = [
    
    path('', Home.as_view(), name='home'),
    
    path('criar/', CriaUsuario.as_view() , name='criar'),
    path('sucesso/', usuario_sucesso, name='sucesso'),
    path('listar/', ListarUsuario.as_view(), name='listar'),
    path('deletar/<int:pk>', DeletaUsuario.as_view(), name='deletar'),
    path('atualizar/<int:pk>', AtualizarUsuario.as_view(), name='atualizar'),
    
    
    path('criar_filme/', CriaFilme.as_view() , name='criar_filme'),
    path('listar_filme/', ListarFilmes.as_view(), name='listar_filme'),
    path('deletar_filme/<int:pk>', DeletaFilmes.as_view(), name='deletar_filme'),
]

projeto_avalia_filmes/urls.py
from django.contrib import admin 
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_avalia_filmes.urls')),  
]

app_avalia_filmes/models.py
from django.db import models

class Usuario(models.Model):
    
    nome_usuario = models.CharField(max_length=30)
    email_usuario = models.EmailField(unique=True)

    def __str__(self):
        return f"Usuário: {self.nome_usuario}"
    
class Filmes(models.Model):
    
    
    titulo = models.CharField(max_length=150)
    genero = models.CharField(max_length=40)
    ano = models.CharField(max_length=4)
    nota = models.DecimalField(decimal_places=1, max_digits=3)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, to_field='email_usuario')
    
    
    def __str__(self):
        return f"Filme: {self.titulo}"

app_avalia_filmes/forms.py
from django import forms
from .models import *

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        
        fields=['nome_usuario', 'email_usuario']
        
        labels={
            'nome_usuario': 'Nome do Usuario',
            'email_usuario': 'Email do Usuario',
        }
        widgets={
            'nome_usuario': forms.TextInput(attrs={'class': 'form-control'}),
            'email_usuario': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        

class FilmeForm(forms.ModelForm):
    class Meta:
        model = Filmes
        
        fields=['titulo', 'usuario', 'nota']
        
        labels={
            'titulo': 'Titulo do Filme',
            'nota': 'Nota de 0 a 10',
            'usuario': 'Email do Usuario',
        }
        widgets={
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'nota': forms.NumberInput(attrs={'class': 'form-control'}),
            'usuario': forms.TextInput(attrs={'class': 'form-control'}),
        }

app_avalia_filmes/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import HttpResponse

from .forms import *
from .models import *

from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View, TemplateView

import requests


def usuario_sucesso(request):
    return render(request, 'sucesso_cria_usuario.html')

def deletar_sucesso(request):
    return render(request, 'sucesso_deleta_usuario.html')

def buscador(titulo):
    url = f"http://www.omdbapi.com/?apikey=89efe44c&t={titulo}"
    buscar = requests.get(url)
    dados = buscar.json()

    if dados.get('Response') == 'True':
        return {
            "titulo": dados.get("Title"),
            "genero": dados.get("Genre"),
            "ano": dados.get("Year"),
        }


class Home(TemplateView):
    template_name='home.html'
        
# CRUD para Usuarios.

class CriaUsuario(CreateView):
    model = Usuario
    
    form_class = UsuarioForm
    template_name = 'cria_usuario.html'
    context_object_name = 'CriaUsuario'
    success_url = reverse_lazy('avaliador:listar')
    
    
class ListarUsuario(ListView):
    model = Usuario
    
    template_name = ('lista_usuario.html')
    context_object_name = 'usuarios'
    
class DeletaUsuario(DeleteView):
    model = Usuario
    
    success_url = reverse_lazy('avaliador:listar')
    template_name = 'confirmar_delete.html'
    context_object_name = 'usuarios'
    
class AtualizarUsuario(UpdateView):
    model = Usuario
    
    form_class = UsuarioForm
    context_object_name = 'usuarios'
    template_name = 'atualizar_usuario.html'
    success_url = reverse_lazy('avaliador:listar')
    

# CRUD para filmes.


class CriaFilme(CreateView):
    model = Filmes
   
    
    form_class = FilmeForm
    template_name = 'cria_filmes.html'
    context_object_name = 'CriaFilme'
    success_url = reverse_lazy('avaliador:listar_filme')
    
    def buscar_filmes(self, form):
        titulo = form.cleaned_data['titulo']
        dados_filme = buscador(titulo)
        if dados_filme:
            form.instance.titulo = dados_filme['titulo']
            form.instance.genero = dados_filme["genero"]
            form.instance.ano = dados_filme["ano"]
    def form_valid(self, form):
        self.buscar_filmes(form)

        if form.is_valid():
            return super().form_valid(form)

    
class ListarFilmes(ListView):
    model = Filmes
    
    template_name = ('lista_filmes.html')
    context_object_name = 'filmes' 
    
class DeletaFilmes(DeleteView):
    model = Filmes
    
    template_name = 'confirmar_delete_filmes.html'
    context_object_name = 'filmes'
    success_url = reverse_lazy('avaliador:listar_filme')
    
class AtualizarFilmes(UpdateView):
    model = Filmes
    
    form_class = FilmeForm
    context_object_name = 'filmes'
    template_name = 'atualizar_filmes.html'
    success_url = reverse_lazy('avaliador:listar_filme')

app_avalia_filmes/templates/atualizar_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atualizar</title>
</head>
<body>
    <h1>Editar Usuário</h1>
    
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Atualizar</button>
        </form>
        <a href="{% url 'avaliador:listar' %}"><button>Voltar</button></a>
</body>
</html>

app_avalia_filmes/templates/confirmar_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sucesso</title>
</head>
<body>
    <h1>Realmente deseja deletar usuario {{ object.nome_usuario }}?</h1>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Deletar</button>
    </form>
    <a href="{% url 'avaliador:listar' %}"><button>Voltar</button></a>
</body>
</html>

app_avalia_filmes/templates/confirmar_delete_filmes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sucesso</title>
</head>
<body>
    <h1>Realmente deseja deletar fime {{ object.titulo }}?</h1>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Deletar</button>
    </form>
    <a href="{% url 'avaliador:listar_filme' %}"><button>Voltar</button></a>
</body>
</html>

app_avalia_filmes/templates/cria_filmes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Filme</title>
</head>
<body>
    <div style="text-align: center;">
        <h1>Cadastrar Novo Filme</h1>
    
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Cadastrar</button>
        </form>
        <br>
        <a href="{% url 'avaliador:listar_filme' %}"><button>Lista</button></a>
        <br><br>
        <a href="{% url 'avaliador:home' %}"><button>Voltar para o inicio</button></a>
    </div>
</body>
</html>

app_avalia_filmes/templates/cria_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Usuario</title>
</head>
<body>
    <div style="text-align: center;">
        <h1>Criar Novo Usuário</h1>
    
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Cadastrar</button>
            
        </form>
        <br>
        <a href="{% url 'avaliador:listar' %}"><button>Lista</button></a>
        <br>
        <br>
        <a href="{% url 'avaliador:home' %}"><button>Voltar para o inicio</button></a>
    </div>
    
</body>
</html>

app_avalia_filmes/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina Inicial</title>
    <link rel="stylesheet" type="home" href="stylesheet.css" media="screen"/>
</head>
<body>
<div style="text-align: center;">
    <h1>Bem Vindo!!!!</h1>
    <p>Bem vindo ao projeto que fiz para o desafio da fabrica,</p>
    <p>eu fiz um avaliador de filmes, onde você cadastra o usuario 
    <p>e com seu usuario voce pode cadastrar o filme e lhe dar a nota</p>
    <br>
    <h3>Inicie</h3>
    <a href="{% url 'avaliador:criar' %}"><button style="padding: 30px;">Cadastrar Usuario</button></a>
    
    <a href="{% url 'avaliador:listar' %}"><button style="padding: 30px;">Lista de Usuarios</button></a>
    <br><br>
    <a href="{% url 'avaliador:criar_filme' %}"><button style="padding: 30px;">Cadastrar Novo Filme</button></a>
    
    <a href="{% url 'avaliador:listar_filme' %}"><button style="padding: 30px;">Lista de Filmes</button></a>
</div>




</body>
</html>

app_avalia_filmes/templates/lista_filmes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Usuarios</title>
</head>
<body>
<div style="text-align: center;">
    <h1>Lista de Filmes Cadastrado por Usuarios</h1>
    <table style="margin: auto; border: 1px solid;">
        <tr>
            <th style="border: 1px solid;">Titulo do Filme</th>
            <th style="border: 1px solid;">Ano de Lançamento</th>
            <th style="border: 1px solid;">Genero</th>
            <th style="border: 1px solid;">Nota</th>
            <th style="border: 1px solid;">Cadastrado pelo usuario</th>
            <th style="border: 1px solid;">Opções</th>
            
        </tr>
        <tr>
        {% for filme in filmes %}
            <td style="border: 1px solid;">{{ filme.titulo }}</td>
            <td style="border: 1px solid;">{{ filme.ano }}</td>
            <td style="border: 1px solid;">{{ filme.genero }}</td>
            <td style="border: 1px solid;">{{ filme.nota }} </td>
            <td style="border: 1px solid;">{{ filme.usuario.nome_usuario }} </td>
            

    
            <td style="border: 1px solid;"><a href="{% url 'avaliador:deletar_filme' filme.pk %}"><button>Deletar</button></a></td>
        </tr>
        {% empty %}
        <li>Nenhum usuário cadastrado. </li>
        {% endfor %}  
    </table>
    <br><br>
    <a href="{% url 'avaliador:criar_filme' %}"><button>Cadastrar Novo Filme</button></a>
    <br><br>
    <a href="{% url 'avaliador:listar' %}"><button>Lista de Usuarios</button></a>
    <br><br>
    <a href="{% url 'avaliador:home' %}"><button>Voltar</button></a>
    
</div>
</body>
</html>

app_avalia_filmes/templates/lista_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Usuarios</title>
</head>
<body>
<div style="text-align: center;">
    <h1>Lista de Usuários</h1>
    <table style="margin: auto; border: 2px solid;">
        <tr>
            <th style="border: 1px solid;">Nome do Usuario</th>
            <th style="border: 1px solid;">Email do Usuario</th>
            <th style="border: 1px solid;">Opções</th>
        </tr>
        {% for usuario in usuarios %}
        <tr>
            <td style="border: 1px solid;">{{ usuario.nome_usuario }}</td>
            <td style="border: 1px solid;">{{ usuario.email_usuario }} </td>

            <td style="border: 1px solid;"><a href="{% url 'avaliador:deletar' usuario.pk %}"><button>Deletar</button></a>
                <a href="{% url 'avaliador:atualizar' usuario.pk %}"><button>Editar</button></a></td>
        </tr>
        {% empty %}
        <li>Nenhum usuário cadastrado.</li> 
        <br>
       
        
        {% endfor %}
        
    </table>
    <br><br>
    <a href="{% url 'avaliador:criar' %}"><button>Cadastrar Novo Usuario</button></a>
    <br><br>
    <a href="{% url 'avaliador:listar_filme' %}"><button>Cadastrar Novo Filme</button></a>
    <br><br>
    <a href="{% url 'avaliador:home' %}"><button>Voltar</button></a>
</div>
</body>
</html>

app_avalia_filmes/templates/sucesso_cria_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sucesso</title>
</head>
<body>
    <h1>Usuario cadastrado com sucesso!!!</h1>

    <a href="{% url 'avaliador:criar' %}"><button>Voltar</button></a>
    <a href="{% url 'avaliador:listar' %}"><button>Lista</button></a>
</body>
</html>